/*
 *	engine/core/ManagedObject.h generated by engine3 IDL compiler 0.60
 */

#ifndef MANAGEDOBJECT_H_
#define MANAGEDOBJECT_H_

#include "engine/orb/DistributedObjectBroker.h"

namespace engine {
namespace core {

class ManagedObject : public DistributedObjectStub {
public:
	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void setLockName(const String& name);

protected:
	ManagedObject(DummyConstructorParameter* param);

	virtual ~ManagedObject();

	void _lock(bool doLock = true);

	void _lock(ManagedObject* obj);

	void _wlock(bool doLock = true);

	void _wlock(ManagedObject* obj);

	void _unlock(bool doLock = true);

	void _setLockName(const String& name);

	friend class ManagedObjectHelper;
};

class ManagedObjectImplementation : public DistributedObjectServant {

public:
	ManagedObjectImplementation();
	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void setLockName(const String& name);

	ManagedObject* _this;

protected:
	virtual ~ManagedObjectImplementation();

	void _setStub(DistributedObjectStub* stub);
	DistributedObjectStub* _getStub();
};

class ManagedObjectAdapter : public DistributedObjectAdapter {
public:
	ManagedObjectAdapter(ManagedObjectImplementation* impl);

	Packet* invokeMethod(sys::uint32 methid, DistributedMethod* method);

	void lock(bool doLock);

	void lock(ManagedObject* obj);

	void wlock(bool doLock);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock);

	void setLockName(const String& name);

protected:
	String _param0_setLockName__String_;
};

class ManagedObjectHelper : public DistributedObjectClassHelper, public Singleton<ManagedObjectHelper> {
	static ManagedObjectHelper* staticInitializer;

public:
	ManagedObjectHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ManagedObjectHelper>;
};

} // namespace core
} // namespace engine

using namespace engine::core;

#endif /*MANAGEDOBJECT_H_*/
