/*
 *	engine/core/ManagedService.cpp generated by engine3 IDL compiler 0.60
 */

#include "ManagedService.h"

/*
 *	ManagedServiceStub
 */

ManagedService::ManagedService(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("ManagedService");
}

ManagedService::~ManagedService() {
}



DistributedObjectServant* ManagedService::_getImplementation() {

	_updated = true;
	return _impl;
}

void ManagedService::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ManagedServiceImplementation
 */

ManagedServiceImplementation::ManagedServiceImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

ManagedServiceImplementation::ManagedServiceImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


ManagedServiceImplementation::~ManagedServiceImplementation() {
}


void ManagedServiceImplementation::finalize() {
}

void ManagedServiceImplementation::_initializeImplementation() {
	_setClassHelper(ManagedServiceHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ManagedServiceImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<ManagedService*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* ManagedServiceImplementation::_getStub() {
	return _this.get();
}

ManagedServiceImplementation::operator const ManagedService*() {
	return _this.get();
}

void ManagedServiceImplementation::lock(bool doLock) {
	_this.getReferenceUnsafe()->lock(doLock);
}

void ManagedServiceImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafe()->lock(obj);
}

void ManagedServiceImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafe()->rlock(doLock);
}

void ManagedServiceImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafe()->wlock(doLock);
}

void ManagedServiceImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafe()->wlock(obj);
}

void ManagedServiceImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafe()->unlock(doLock);
}

void ManagedServiceImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafe()->runlock(doLock);
}

void ManagedServiceImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("ManagedService");

}

void ManagedServiceImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		String _name;
		_name.parseFromBinaryStream(stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ManagedServiceImplementation::readObjectMember(stream, _name)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ManagedServiceImplementation::readObjectMember(ObjectInputStream* stream, const String& _name) {
	if (ManagedObjectImplementation::readObjectMember(stream, _name))
		return true;


	return false;
}

void ManagedServiceImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ManagedServiceImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ManagedServiceImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	String _name;
	int _offset;
	uint32 _totalSize;

	return _count + 0;
}

/*
 *	ManagedServiceAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ManagedServiceAdapter::ManagedServiceAdapter(ManagedService* obj) : ManagedObjectAdapter(obj) {
}

void ManagedServiceAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		throw Exception("Method does not exists");
	}
}

/*
 *	ManagedServiceHelper
 */

ManagedServiceHelper* ManagedServiceHelper::staticInitializer = ManagedServiceHelper::instance();

ManagedServiceHelper::ManagedServiceHelper() {
	className = "ManagedService";

	Core::getObjectBroker()->registerClass(className, this);
}

void ManagedServiceHelper::finalizeHelper() {
	ManagedServiceHelper::finalize();
}

DistributedObject* ManagedServiceHelper::instantiateObject() {
	return new ManagedService(DummyConstructorParameter::instance());
}

DistributedObjectServant* ManagedServiceHelper::instantiateServant() {
	return new ManagedServiceImplementation(DummyConstructorParameter::instance());
}

DistributedObjectAdapter* ManagedServiceHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ManagedServiceAdapter(static_cast<ManagedService*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

