/*
** Copyright (C) 2007-2019 SWGEmu
** See file COPYING for copying conditions.
*/

package engine.core;

import engine.core.ManagedObject;

//@nonTransactional
class ManagedService extends ManagedObject {
}
