/*
Copyright (C) 2007 <SWGEmu>. All rights reserved.
Distribution of this file for usage outside of Core3 is prohibited.
*/

package engine.core;

class ManagedObject {
	@nativeStub 
	public native void lock(boolean doLock = true);
	
	@nativeStub 
	public native void lock(ManagedObject obj);

	@nativeStub 
	public native void wlock(boolean doLock = true);

	@nativeStub 
	public native void wlock(ManagedObject obj);
	
	@nativeStub 
	public native void unlock(boolean doLock = true);
	
	@nativeStub 
	public native void setLockName(final string name);	
}
