/*
** Copyright (C) 2007-2019 SWGEmu
** See file COPYING for copying conditions.
*/

package testsuite3.tests;

import engine.core.ManagedObject;

include system.util.Vector;

//@lua
@json
class TestIDLClass extends ManagedObject {
	private int value;

	@dereferenced
	Vector<int> testVector;

	@weakReference
	protected TestIDLClass parent;

	public TestIDLClass(int val) {
		value = val;

		testVector.add(-1);
		testVector.add(5);
	}

	public int getValue() {
		return value;
	}

	public void setValue(int val) {
		value = val;
	}

	public void setValue2(int val1, int val2) {
	    value = val2;
	}

	public void setParent(TestIDLClass val) {
	    parent = val;
	}

	public void testShit(@dereferenced final Vector<int> val) {
	    //testVector = val;
/*
        int valSize = (int) val.size();

	    for (int i = 0; i < valSize; ++i) {
	    //    testVector.add(val.get(i));
	    }
*/
	}

    @local
	public Vector<int> getTestVector() {
	    return testVector;
	}

    @weakReference
	public TestIDLClass getParent() {
	    return parent;
	}

    @async
	public void asyncTest() {

	}
}
