/*
 *	engine/util/Observable.h generated by engine3 IDL compiler 0.60
 */

#ifndef OBSERVABLE_H_
#define OBSERVABLE_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

namespace engine {
namespace log {

class Logger;

} // namespace log
} // namespace engine

using namespace engine::log;

#include "engine/core/ManagedObject.h"

#include "engine/util/Observer.h"

#include "engine/util/ObserverEventMap.h"

namespace engine {
namespace util {

class Observable : public ManagedObject {
public:
	void notifyObservers(unsigned int eventType, ManagedObject* arg1 = NULL, long long arg2 = 0);

	void registerObserver(unsigned int eventType, Observer* observer);

	void dropObserver(unsigned int eventType, Observer* observer);

	int getObserverCount(unsigned int eventType);

	DistributedObjectServant* _getImplementation();

	void _setImplementation(DistributedObjectServant* servant);

	bool _isCurrentVersion(ManagedObjectImplementation* servant);

protected:
	Observable(DummyConstructorParameter* param);

	virtual ~Observable();

	friend class ObservableHelper;
};

} // namespace util
} // namespace engine

using namespace engine::util;

namespace engine {
namespace util {

class ObservableImplementation : public ManagedObjectImplementation {
protected:
	ObserverEventMap observerEventMap;

public:
	ObservableImplementation();
	ObservableImplementation(DummyConstructorParameter* param);

	void notifyObservers(unsigned int eventType, ManagedObject* arg1 = NULL, long long arg2 = 0);

	void registerObserver(unsigned int eventType, Observer* observer);

	void dropObserver(unsigned int eventType, Observer* observer);

	int getObserverCount(unsigned int eventType);

	WeakReference<Observable*> _this;

	operator const Observable*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~ObservableImplementation();

	Object* clone();
	Object* clone(void* object);
	void free();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const String& name);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class Observable;
	friend class TransactionalObjectHandle<ObservableImplementation*>;
	friend class TransactionalObjectHeader<ObservableImplementation*>;
};

class ObservableAdapter : public ManagedObjectAdapter {
public:
	ObservableAdapter(ObservableImplementation* impl);

	Packet* invokeMethod(sys::uint32 methid, DistributedMethod* method);

	void notifyObservers(unsigned int eventType, ManagedObject* arg1, long long arg2);

	void registerObserver(unsigned int eventType, Observer* observer);

	void dropObserver(unsigned int eventType, Observer* observer);

	int getObserverCount(unsigned int eventType);

};

class ObservableHelper : public DistributedObjectClassHelper, public Singleton<ObservableHelper> {
	static ObservableHelper* staticInitializer;

public:
	ObservableHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ObservableHelper>;
};

} // namespace util
} // namespace engine

using namespace engine::util;

#endif /*OBSERVABLE_H_*/
