/*
Copyright (C) 2007 <SWGEmu>. All rights reserved.
Distribution of this file for usage outside of Core3 is prohibited.
*/

package engine.util;

include engine.core.ManagedObject;
//import engine.core.ManagedReference;

import engine.log.Logger;

//include engine.util.SessionFacadeType;

class Facade extends ManagedObject implements Logger {
	public Facade() {
		Logger.setLoggingName("Facade");
	}
	
	public abstract int initializeSession() {
		return 0;
	}
	
	public abstract int cancelSession() {
		return 0;
	}
	
	public abstract int clearSession() {
		return 0;
	}
}
